definitions:
  control.CreateResponse:
    properties:
      message:
        type: string
    type: object
  control.rErrorResponse:
    properties:
      "200":
        type: string
      "400":
        type: string
      "500":
        type: string
    type: object
  main.mErrorResponse:
    properties:
      "200":
        type: string
      "400":
        type: string
      "500":
        type: string
    type: object
  service.Address:
    properties:
      city:
        type: string
      geo_lat:
        type: string
      geo_lon:
        type: string
      house:
        type: string
      street:
        type: string
    type: object
  service.ResponseAddress:
    properties:
      suggestions:
        items:
          properties:
            data:
              $ref: '#/definitions/service.Address'
          type: object
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: Этот эндпоинт позволяет получить адрес по наименованию
  title: Address API
  version: "1.0"
paths:
  /api/book:
    get:
      consumes:
      - application/json
      description: This description created new SQL user
      produces:
      - application/json
      responses:
        "200":
          description: List successful
          schema:
            $ref: '#/definitions/control.CreateResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/control.rErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/control.rErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/control.rErrorResponse'
      summary: List SQL book
      tags:
      - TakeBook
  /api/book/take/{index}:
    post:
      consumes:
      - application/json
      description: This endpoint allows you to get geo coordinates by address.
      parameters:
      - description: Book INDEX
        in: path
        name: index
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Успешное выполнение
          schema:
            $ref: '#/definitions/service.ResponseAddress'
        "400":
          description: Ошибка запроса
          schema:
            $ref: '#/definitions/main.mErrorResponse'
        "500":
          description: Ошибка подключения к серверу
          schema:
            $ref: '#/definitions/main.mErrorResponse'
      security:
      - BearerAuth: []
      summary: Get Geo Coordinates by Address
      tags:
      - TakeBook
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
